### ISSUE TITLE
Client can call Service without being granted permissions in Azure AD App Registration

### ISSUE THREAD

**Issue by LawrenceSmith1437** [Azure-Samples/active-directory-dotnetcore-daemon-certificate-credential#10]
This might be more of a question or an observation about how Azure AD app registration permissions work.

In all the other "ToDoList" walkthroughs I've done, the client needs to be granted permission in AzureAD to allow it to talk to the service.  Yet in this walkthrough, I realized that step seems to be missing. YET the client was able to successfully call the service anyway.

Is it actually not necessary? Somehow I think in the other walkthroughs it WAS necessary and didn't work till permissions had been granted. So I have to ask: Why does this walkthrough work?

**Comment by LawrenceSmith1437** [comment]
Additional note:  I did find the section where you grant permissions. Readers fatigue.  However, I skipped this section, and confirmed that at present my client had not been granted any permission to the server, yet client can call service successfully through Azure AD, so my question remains, shouldn't it fail?

**Comment by jmprieur** [comment]
Fixed by adding authentication: https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-certificate-credential#secure-your-web-api-by-defining-application-roles-permission
