### ISSUE TITLE
Returns 401 using NET Core 2.2

### ISSUE THREAD

**Issue by 101michael** [Azure-Samples/active-directory-dotnetcore-daemon-certificate-credential#11]
I recreate the daemon project using NET Core 2.2 and for some reason, the client service returns 401.

Setup are all identical except the Framework. Is there any version of the code that works for the later framework?

**Comment by jmprieur** [comment]
Daemon do not allow interaction. Therefore no consent can be presented via a UI and accepted to use the service app. You would need to:
1. Navigate to the Microsoft identity platform for developers [App registrations](https://go.microsoft.com/fwlink/?linkid=2083908) page.
1. Find your application
1. In the **API permissions** page, click the Grant/revoke admin consent for {yourtenant} button, and then select Yes when you are asked if you want to grant consent for the requested permissions for all account in the tenant. You need to be an Azure AD tenant admin to do this.

**Comment by jmprieur** [comment]
Todo: update the readme.md to have steps with the new app registration

**Comment by TiagoBrenck** [comment]
The Readme.md has been updated with this step:

> At this stage permissions are assigned correctly but the client app does not allow interaction. Therefore no consent can be presented via a UI and accepted to use the service app. Click the Grant/revoke admin consent for {tenant} button, and then select Yes when you are asked if you want to grant consent for the requested permissions for all account in the tenant. You need to be an Azure AD tenant admin to do this.

@101michael the sample has been updated to Core 2.2 and we didnt find any problems.
Are you still facing problems with NET Core2.2?
