### ISSUE TITLE
Application permission vs Delegated permission

### ISSUE THREAD

**Issue by tannguyen3** [Azure-Samples/active-directory-dotnetcore-daemon-certificate-credential#14]
It seems like AzureAD got updates and now delegated permission and application permission cannot have the same value. 
At step [Add an app role to the manifest](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-certificate-credential#add-an-app-role-to-the-manifest) doesn't work as the error
![image](https://user-images.githubusercontent.com/10743872/62838192-6c26ff00-bc3e-11e9-9263-0ca836f453c6.png)

The fix could be remove step 6 of [Register the service app (TodoListService-Core-Cert)](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-certificate-credential#register-the-service-app-todolistservice-core-cert) since it only registers an delegated permission.

**Comment by TiagoBrenck** [comment]
Fixed
