### ISSUE TITLE
Would this sample work with Mac or Linux ( using (X509Store store = new X509Store(StoreName.My, StoreLocation.CurrentUser)))  ?

### ISSUE THREAD

**Issue by nigel-dewar** [Azure-Samples/active-directory-dotnetcore-daemon-certificate-credential#4]
Hi There,

thanks for the sample.

I noticed you are using these kinds of references 

 using (X509Store store = new X509Store(StoreName.My, StoreLocation.CurrentUser))

Im a windows user, but planning on testing .net core on linux.

I dont reckon the above code snippet referencing storename.my and storelocation.currentuser would work.

How would one deal with this on linux? Would it not be better to reference the certificate directly from a specified file path?  just a guess

cheers

Nige

**Comment by jmprieur** [comment]
Yes, you would get the certificate with another way, for instance by lading the certificate from a file with the `X509Certificate2(string fileName)` constructor
