### ISSUE TITLE
Step 7 of Deploy to Azure is incorrect

### ISSUE THREAD

**Issue by LawrenceSmith1437** [Azure-Samples/active-directory-dotnetcore-daemon-certificate-credential#9]
in the step to deploy to Azure: 
https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-certificate-credential#create-and-publish-the-todolistservice-to-an-azure-web-site

Step 7 says "Visual Studio will publish the project and automatically open a browser to the URL of the project. If you see the default web page of the project, the publication was successful."

The web project itself doesn't have a webpage, it's api only.

**Comment by jmprieur** [comment]
Thanks @SgtSapmCan!
I just fixed the README.md
